### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jaanos** [julitag/druzabne_igre#2]
Na repozitorij se vam je izmuznilo kar nekaj datotek, ki tja ne sodijo. Svetujem, da v `.gitignore` dodasta naslednje vrstice:
```gitignore
__pycache__
.vscode
env
*.log
```
Ustrezne datoteke še pobrišita iz repozitorija - torej vse mape `__pycache__` (prevedene Pythonove datoteke), mapo `.vscode` (metapodatki urejevalnika), mapo `env` (virtualno okolje) in datoteko `debug.log` (dnevnik razhroščevanja). Prav tako imata v mapi `pythonpodatki` datoteko `chromedriver.exe` - sklepam, da tja ne sodi, tako da jo pobrišita.

V mapi `env` je virtualno okolje, torej vse Pythonove knjižnice, ki jih potrebujeta. Da ga ne izgubita, svetujem, da eden od vaju premakne to mapo drugam, naredi commit, v kateri se pobriše, nato pa mapo vrne na mesto (z ustrezno vrstico v `.gitignore` je git več ne bo predlagal za vključitev v commit). Pred pullom na drugih računalnikih mapo skopirajta drugam, nato naredita pull in mapo vrneta.

Svetujem, da v `README.md` napišeta navodila za vzpostavitev virtualnega okolja, pri čemer potrebne knjižnice zbereta v datoteko [`requirements.txt`](https://medium.com/@boscacci/why-and-how-to-make-a-requirements-txt-f329c685181e) (ali pa uporabita kakšno drugo rešitev, kot je predlagano na vrhu strani). Tako se bo uporabnik sam odločil, ali bo uporabil virtualno okolje oziroma bo knjižnice namestil v sistemsko namestitev Pythona.

**Comment by gasperletnar** [comment]
Chromedriver.exe je del programa za zbiranje podatkov iz spletnih strani, uporabljen je v skripti /pythonpodatki/podatky.py
Ostalo je popravljeno.

**Comment by jaanos** [comment]
V redu, bom kar zaprl issue (lahko seveda to tudi sama storita, ko razrešita problem).

Zunanjih programov se naj sicer načeloma ne bi dajalo na repozitorij - če je potreben kak zunanji program ali knjižnica, se to navadno navede v `README.md`, da lahko uporabnik poskrbi za to. V tem primeru to sicer velja samo za skripto za pridobivanje podatkov, tako da ni bistveno, da se tako naredi.
