### ISSUE TITLE
tabela

### ISSUE THREAD

**Issue by gasperletnar** [julitag/druzabne_igre#3]
Pozdravljeni,
naredila sva osnova.html template in izvedla ostale popravke, ki ste jih priporočili, sedaj bi registracija morala delovati. Na osnovni strani, takoj po uspešni registraciji, je tabela z igrami. Znotraj tabele piše "Showing 10 entries" - to je del javascripta,. Kako lahko to spremeniva, da bo pisalo v slovenščini?

**Comment by jaanos** [comment]
Popraviti bo treba datoteko `static/js/demo/datatables-demo.js`, npr.
```javascript
// Call the dataTables jQuery plugin
$(document).ready(function() {
    $('#dataTable').DataTable( {
        "language": {
            "lengthMenu":   "Prikaži _MENU_ vnosov",
            "zeroRecords":  "Ni zadetkov",
            "search":       "Iskanje:",
            "paginate": {
                "first":      "Prva",
                "last":       "Zadnja",
                "next":       "Naslednja",
                "previous":   "Prejšnja"
            },
        }
    } );
});
```
Zgornja koda poskrbi, da se tabela z atributom `id="dataTable"` prikaže kot DataTable s podanimi prevodi.

Vidim, da sedaj uporabljata `rebase`, a se koda za navigacijo (stranska in zgornja vrstica) vseeno ponavlja. `rebase` lahko uporabita tudi večkrat - svetujem torej, da naredita predlogo npr. `navigacija.html`, ki bo klicala `rebase` na `osnova.html`, pri straneh, kjer je prikazana navigacija (verjetno kar vse razen prijave in registracije), pa namesto tega kličita `rebase` na `navigacija.html`.

**Comment by gasperletnar** [comment]
To ne deluje, sem že včeraj gledal. Se morda ta koda shranjuje v browser, pa moram resetirati oziroma pobrisati kakšne cookieje v Chromeu?

**Comment by gasperletnar** [comment]
Pa je nekaj povezano s tem, ker sem sedaj sprobal se na Internet Explorerju, tam pa so spremembe opazne.

**Comment by jaanos** [comment]
Verjetno se pomožne datoteke res shranijo v brskalnikov medpomnilnik. Poskusi ponovno naložiti stran s Ctrl+F5.

**Comment by gasperletnar** [comment]
Ja, sedaj deluje, hvala.
