### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by gasperletnar** [julitag/druzabne_igre#4]
Pozdravljeni,

najin projekt je zaključen. Bi ga lahko prosim ocenili?

Lep pozdrav,

Gašper Letnar

**Comment by jaanos** [comment]
Dodal bom povezavo na repozitorij predmeta, z @alenFMF pa se lahko domenita za termin zagovora, kjer bosta tudi prejela končno oceno. Če bosta do takrat še kaj spreminjala, mi javita, da posodobim povezavo.

Imam samo nekaj pripomb estetske narave:
* Na obrazcu za prijavo sta polji za uporabniško ime in e-poštni naslov izpolnjeni z nizom *None* - poskrbita torej, da se vrednost `None` ne izpisuje.
* Če noben uporabnik še ni ocenil igre, bo bolje, če vrstice z oceno sploh ne izpišeta, kot če piše, da je ocena *None/10*.
* Pri seznamu iger sortiranje po času igranja in minimalni starosti ne deluje pravilno (načeloma niti po številu igralcev, a se pri trenutnih podatkih to ne pokaže). Kako se stolpec sortira, lahko kontrolirata z atributom `data-order` značke `<td>`, npr.
```html
<td data-order="{{(0 if igra[2] is None else igra[2])}}">
```
Pomembno je, da so vse vrednosti številske (če se kje pojavi kak `None` ali kaj drugega, se bodo podatki urejali kot besedilo). Zgornji primer bi sicer poskrbel samo za urejanje po minimalnem številu igralcev - da bi ustrezno urejali po obojem, bi bilo potrebno sestaviti ustrezno vrednost (npr. min. št. igralcev * največje max. št. igralcev + max. št. igralcev - in podobno pri trajanju). Lahko bi morda že poizvedbo napisala tako, da vama vrača tudi te vrednosti.

Mimogrede: veliko bolj bo berljivo, če v zanki `for` igro kar takoj razbijeta na ustrezna polja, npr.
```python
%for serijska, ime, min_igralcev, max_igralcev, min_cas, max_cas, leto_izdaje, starost, dodatek in igre:
```
Druga možnost bi bila uporaba imenskih indeksov stolpcev (kar imata omogočeno, glede na to, da uporabljata `DictCursor`) - v obeh primerih bo koda veliko bolj berljiva, kot če uporabljata številske indekse.

**Comment by gasperletnar** [comment]
Prvi dve pripombi sta odpravljeni, ne razumem pa kaj mislite glede tretje. Ko sem vnesel dve poljubni vrednosti v število igralcev in minimalno starost, sem dobil razvrščene igre, urejene po njihovi serijski številki v katero so vnesene v bazo.

**Comment by jaanos** [comment]
Mislil sem glede sortiranja podatkov v prikazani tabeli (tako na prvi strani kot pri iskanju) s klikom na puščice v naslovu stolpca.

**Comment by gasperletnar** [comment]
Sem uredil. Lahko prosim posodobite povezavo do projekta?

**Comment by jaanos** [comment]
Ne vidim še commita, ki bi to popravil. Si morda pozabil na push?

**Comment by gasperletnar** [comment]
Zdaj je.

**Comment by jaanos** [comment]
V redu, sem posodobil.
